databases:
  - name: mysetedb
    plan: free
    databaseName: bookproject2
    user: hibari

services: 
  - type: web
    plan: free
    name: hibari
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn bookproject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: mysitedb
        property: connectionString
    - key: WEB_CONCURRENCY
      value: 4